### ISSUE TITLE
Support for Scalable Vector Graphics(SVG)

### ISSUE THREAD

**Issue by OlavStornes** [astoff/devdocs.el#11] opened 2021-12-08 07:59 UTC
Hi! First off, i'm really thankful for this project. Having documentation offline in emacs helps me a lot.

When querying for a page with pictures on devdocs (example: [SQLITE - VACUUM](https://devdocs.io/sqlite/lang_vacuum)), i can see an svg-element which corresponds to the original documentation. However, this appears to not be visible when using devdocs-mode via emacs.

I'm not sure if this even is feasible or practical, but it could _maybe_ be of value for someone else than me as well?

**Comment by astoff** [comment] 2021-12-15 11:33
It is certainly feasible and practical. In fact, I'm not sure why this happens, since Emacs (respectively shr.el) is able to display SVG images.

You can check out the SVG code in the file lang_vacuum.html (under ~/.emacs.d/devdocs/sqlite). Perhaps it's slightly malformed, or incompatible with Emacs for some other reason. I'd encourage you to file a bug in Emacs if that's the case.

Since this is not a bug in this package, I'll close this ticket.

**Closed by astoff** 2021-12-15 11:33 UTC
